### ISSUE TITLE
Resolution Issues?

### ISSUE THREAD

**Issue by greenbrad** [csiqueirasilva/PoEController#12]
No longer working? Resolution set to 1920x1080 and won't work no matter what.

**Comment by csiqueirasilva** [comment]
I'm using 1920x1080 and it seems only the basics of the program are working atm. Maybe GGG repackaged some images in the GGPK file.

Since the beginning, I said this was just a quick hack to get controllers working and the method used is kind of unreliable (reading screen pixels). I'm taking a look into the BOT program Exile-Bot to see if it is possible to read the state of the game (ie: what menus are open) from the game's memory. This would make things more "bulletproof".

Also, I'm waiting the xbox one game to release to see what they did to controllers there. Maybe it would be for the best to try to adapt their controls into PoEController. 

The future of PoEController relies on the memory reading method working (and be legal to use).

**Comment by csiqueirasilva** [comment]
application no longer tied to specific resolutions; as the pixel reading was dropped entirely - some minor graphical bugs might still happen tho
