### ISSUE TITLE
Add a developer guide

### ISSUE THREAD

**Issue by m0rth1um** [csiqueirasilva/PoEController#21]
Can you add a guide how to compile this app?
I would like to add support for my XBOX ONE Controller but did not get the NWJS app to start or to compile

**Comment by csiqueirasilva** [comment]
Hello @m0rth1um !

I don't have time yet to create a full dev guide for this, but if youre willing to build this, these steps should suffice:

- clone the repo
- "npm install" it
- (this part sucks) compile node-hid and robotjs with nw-gyp (requires additional flags in the command to proper detect your msvs libraries and python2.7)
- (optional) install nwjs with nwbuild (it install nwjs as the sdk version; required to use the console for debugging)
- run the application with the command
`node_modules\nw\nwjs\nw.exe . --disable-gpu-compositing --force-cpu-draw`
or, if debugging
`nwbuild -r . --disable-gpu-compositing --force-cpu-draw`

**Comment by csiqueirasilva** [comment]
@tpiardi from memory (its been a while, i dont remember some things from
the top of my head):

refer to https://github.com/nwjs/nw.js/wiki/build-native-modules-with-nw-gyp
(or the newer 0.13+ docs) on how to compile libraries (robotjs and node-hid
will be used in this case).

globally install nw-gyp and run the "nw-gyp configure ..." (check the exact
command in their wiki, in the link above) in the node-hid and robotjs
directories. it will compile a binding.gyp file that should exist somewhere
in the poecontroller directory structure (check the installed version to
see the correct directory).

running the nw-gyp configure will be a bit troublesome and there will be
some additional configurations to be done, if it isnt finding your msvs
libraries and/or python.

**Comment by chastise** [comment]
Apologies for the necro, I'm trying to follow these instructions and believe I've made it past the nw-gyp stage. I'm trying to add two entries to the PID list and the build locally. I suspect I have the same controller as OP, and based on http://www.linux-usb.org/usb.ids my guess is that the following need to be added:

`02ea  Xbox One S Controller`
`02fd  Xbox One S Controller [Bluetooth]`

I've gotten to the "run the application" with `node_modules\nw\nwjs\nw.exe . --disable-gpu-compositing --force-cpu-draw` stage, but the window isn't rendering and I keep seeing the error `[4596:19352:0915/163649.020:ERROR:gpu_process_transport_factory.cc(1016)] Lost UI shared context.`. I've done a bunch of googling, but I'm a total node/nwjs newbie and have hit my limit on trying to triage. I've also tried building and running the resulting executable, but have had no luck there either.

I know the project is not being actively worked on, but this is the only software I can use to play PoE due to accessibility issues (at least until they add it natively), so any help so I can continue to self-serve would be greatly appreciated.

**Comment by csiqueirasilva** [comment]
Hey mate, thanks for the interest in the project. There's a new
poe-controller on the scene, that was recently released:
https://github.com/Zhadok/poe-controller

Id have to ask for you to check it out instead of my project. Currently im
working on poe-skills-overlay (
https://github.com/csiqueirasilva/poe-skills-overlay), that displays easier
to track flasks and skills icons. Hopefully another version of it will get
ready before Heist.

If GGG gave more resources for me (and the community) to keep this up to
date, i'd have loved to keep this going. However, without such resources,
it was very hard. Received many replies from players that used this
software to play due to their own issues with accessibility and it really
moved me. Initially, I only went to make this software to play PoE on the
couch, but it became so much more to others that it is times like these
that one can see the weight of their own actions in the world.

Please report back if you can't get to use Zhadok's version for some
reason. I might be able to cook something in the next couple days, if you
give me exactly what you need.

Em ter., 15 de set. de 2020 às 20:40, chastise <notifications@github.com>
escreveu:

**Comment by chastise** [comment]
Hey! Thanks for the share! I haven't been able to get it working (the application isn't registering a number of inputs and seems to lose focus easily), but I appreciate the increased customization it's trying to offer.

I _believe_ the only change I was looking to make is to add the new USB PIDs so that it registers the controllers msft is currently selling. It looks like they've moved fully to the Xbox one bluetooth-y models. I can open a PR with the changes I'm thinking of if you'd like, though they would be untested since I can't get the dev environment working on my end yet.

As a fallback, I can attempt to buy an older controller of the model I used to have (360?), and hope that works.

Either way, yeah I wanna echo what other folks have been saying. I wouldn't have been able to play this game for the past two years without this software. I basically plan builds around it. I really appreciate that it's let me play when I've had to give up so many other games that I love.

If there's something I can do to get my local build working sufficiently, I would prefer to self serve. I know you're strapped for time, and I don't want to take away from efforts on your other projects any more than I already have. Thanks!

**Comment by csiqueirasilva** [comment]
Tried getting the project to work again and wasnt able to. Im trying to move from nwjs to electronjs, since it doesnt require the nw-gyp step. Lets hope I can finish this by tomorrow (and that it works at all).

Will attempt to create some interface that lists your hid devices and let you create your own bindings for it. This should fix any issues with unknown gamepads for the future (remember: lets hope all this works!).

**Comment by chastise** [comment]
Woah! That's awesome to hear! I don't know enough about nwjs vs electron to really understand the work involved, but I appreciate the effort so much! If electron is easier to set up (once it's moved over) I will gladly contribute to the project as well.

**Comment by csiqueirasilva** [comment]
Hello @chastise . Since your previous messages, Ive been working non-stop to get the app working again. Its on a state that im confident it will be available today or early tomorrow. Decided to already post this since this since it is required that you provide some information for me to get your gamepad working. Also, im closing this issue since this post works as a dev guide for the current iteration of the application. Please post your gamepad configuration in a new issue if you'd like. I can help you get it working before tomorrow, for Heist league.

--------------------------------------------------------

As of today, rebuilding the app with Electron required the following steps:

clone from github
```
git clone https://www.github.com/csiqueirasilva/PoEController
```

to the usual install command to install dependencies
```
npm install
```

this replace the old nw-gyp stuff:
```
.\node_modules\.bin\electron-rebuild.cmd
```

to initialize the application:
```
npm start
```

Went on to trim the application of bloated code and left only the ARPG input mode. Now if your controller is not detected, it opens a new interface where you can select the detected usb devices and check the pid/vid for it (and also it writes the first 16 bytes of data from the buffer, so you can do some quick input tests and check whats been read in binary data). You need to manually add vid/pid to the configuration file in **%appdata%\PoeController\user-settings.json**, and add the file **src/game/inputs/.i<vid>_<pid>.js** that translates data received from your device to the input methods in the application. I'm shipping it with **i1356_2508.js** which is what I have for my PS4 gamepads (my old PS3 gamepad died some years back). Found this very instructive reference for PS4 gamepads. If you can find some reference for yours and doesnt know how to add it, I could do it, but only by a couple hours before Heist league launches.

I believe that if some other PS4 controller has for some reasons a different PID, the file for it could be created and the one stated above could be imported for its methods to be exported in **modules.exports**. Something like this below, havent tested yet:

```
/* let this be a new configuration file, say i1356_0000.js */
const workingInput = require('./i1356_2508');
module.exports = workingInput;
```
