### ISSUE TITLE
DPAD isn't working.

### ISSUE THREAD

**Issue by warst1993** [csiqueirasilva/PoEController#24]
My XBOX 360 Wireless controller isn't registering the DPAD inputs. I am using this controller for playing Zelda BoTW as well, DPAD works there, PC is clearly receiving the input, but in PoE it isn't registered.  Everything else works fine, ingame.
My controller is Microsoft Wireless Common Controller PC/X360 USB Port JR9-00010.
Thank you, if you need anything else to resolve the issue, contact me.

**Comment by csiqueirasilva** [comment]
im glad you could make the program work at all with your wireless
controller. some people contacted me recently about this issue and they
couldnt even get the controller to be recognized.

the issue is simple to solve, but becomes hard as i dont have an xbox
wireless controller to test it myself.

maybe you could try to edit the file game/Controller.js and get the correct
bindings (numbers) for your controller? If you do this (and pull request
it), I can ship an executable that uses those bindings if it detects your
lind of controller.

**Comment by warst1993** [comment]
I'll try. Will update tomorrow.

**Comment by csiqueirasilva** [comment]
should work under the new feature: xinput mode
