### ISSUE TITLE
Adding XBOX One Controller Codes

### ISSUE THREAD

**Issue by chastise** [csiqueirasilva/PoEController#32]
While it seems less comprehensive than the PS4 spec you posted, [this](https://docs.microsoft.com/en-us/windows/win32/xinput/directinput-and-xusb-devices) seems to be roughly the equivalent for xbox controllers. It _seems_ like they all use a similar schema, but I'm not sure. It's my hope that since some xbox controllers already worked, this too will work once the pid/vid are added for detection.

Is there a new commit with the electron code and the inputs file that I can pull?

Re: [build instructions here](https://github.com/csiqueirasilva/PoEController/issues/21#issuecomment-694307532): When I try the node-rebuild on the current commit, it fails to run the electron-rebuild command (after installing a electron and electron-rebuild). More node-gyp config errors. It's likely my environment isn't properly configured since I only installed node for this project and I'm a beginner, but also it seems the node-gyp errors on windows are common and varied in their specific solutions, so after a second afternoon of troubleshooting I think it's unlikely I'll sort them out.

**Comment by csiqueirasilva** [comment]
I'm just about to finish the updates and commit them. Everything is running on my PS4 gamepad, as far as I could test. One big difference is that I had to offset the data received from node-hid when the gamepad as on bluetooth mode. 

From what I understood (did minimal reading), its the bluetooth headers.

I'll just push what I have to the repository, so you can clone it and check on screen how your gamepad behaves.

**Comment by csiqueirasilva** [comment]
Hey @chastise 

Added more info on https://github.com/csiqueirasilva/PoEController/blob/master/developers.md ; 

Maybe could you send a screenshot of that screen with the gamepad on the following settings:

- no keys pressed
- left axis to the left
- left axis to up
- right axis to the right
- right axis to up
- each pov (dpad) pressed individually, check if the corners are detected as a separate input too
- each shoulder trigger (rb, lb, rt, lt) pressed individually
- each button (x, y, a, b) pressed, individually
- "start" button pressed
- "select" button pressed

With this we might figure out in what positions of the data buffer the changes are made and develop an input script for your gamepad.

**Comment by chastise** [comment]
Thank you! I'm glad to hear it's working on your end!

I was struggling to build locally, but eventually got something to work with `npm run dist` (the electron rebuild step was NOT working, it kept failing on node-hid with some cryptic errors that I still haven't resolved anywhere on google). 

I am able to see the UX as displayed [here ](https://github.com/csiqueirasilva/PoEController/blob/master/screenshots/hardwareconfig1.png) and when I select my controller from the dropdown ("Xbox Bluetooth Gamepad") I get a HID, PID and what looks to be 14 bytes of output. I'm typing the outputs into a sheet now, and I'll share the resulting CSV shortly!

**Comment by csiqueirasilva** [comment]
OK. Im keen on receiving the results! Lets get your ending working too!

**Comment by chastise** [comment]
I just shared a doc with the email address attached to your github account. Also, I was able to find [this page](https://docs.microsoft.com/en-us/windows/win32/xinput/directinput-and-xusb-devices) while searching around yesterday. It looks like the information under "game pad" is what we're looking for, and it may explain some of the ambiguity with the trigger buttons that I was observing.

**Comment by csiqueirasilva** [comment]
I didnt receive the google docs share. Please send it again to
csiqueirasilva@gmail.com

**Comment by chastise** [comment]
Just kidding, I didn't hit send >.> It should be shared now!

**Comment by chastise** [comment]
As an additional note, when I run the controller through USB (rather than bluetooth) the outputs appear to be identical. The VID is the same (045E) and the PID is 02FF ; In bluetooth the PID is 02E0. Those do not match the values I shared in the other thread, so I'm glad I checked!

**Comment by csiqueirasilva** [comment]
Thanks for sharing the PID and VID. I'll try to code what you just sent and
commit it. Will reply to this post when that is done.

Some fine tuning might be needed on your end since i'm doing this blindly.

Em sex., 18 de set. de 2020 às 00:12, chastise <notifications@github.com>
escreveu:

**Comment by csiqueirasilva** [comment]
Can you confirm that there's no difference in the binary data received in
bluetooth and cable mode? Are positions the same?

Em sex., 18 de set. de 2020 às 00:14, Caio Silva <csiqueirasilva@gmail.com>
escreveu:

**Comment by chastise** [comment]
Yep, they appear to be identical. 

Also, I forgot about L3 and R3, I'm going to add them to the list right now!

**Comment by csiqueirasilva** [comment]
Hello.

Just pushed the files to github. The shoulder keys are commented out, since
I couldnt figure it out from the spreadsheet.

The files are:

https://github.com/csiqueirasilva/PoEController/blob/master/src/game/inputs/i1118_767.js
https://github.com/csiqueirasilva/PoEController/blob/master/src/game/inputs/i1118_736.js

Not sure about the javascript semantics on i1118_767.js tho. Also, the VID
and PID are on decimal values, so those should be on your
user-settings.json (Im using decimal values for my PS4 controllers, seems
thats what node-hid gave out as pid and vid).

Also try to set debug to true while running this, so you can get a bit more
info on command prompt.

Em sex., 18 de set. de 2020 às 00:23, chastise <notifications@github.com>
escreveu:

**Comment by chastise** [comment]
Couple quick notes: 

- When I launch with 767 (wired) it gives me an error about not being able to find the import for i1118_736.js
- If bluetooth isn't set to true when I launch with bluetooth, no input is detected (not sure what the flag is doing so I wanted to mention this).
- When I launch with 736, I get some degree of functionality. Specifically from debug: I can detect keypresses for all buttons and bumpers. Triggers don't work (makes sense!). Left stick sort-of-works (moves cursor in a circle around the center), right stick doesn't seem to be doing anything. That said, I think the noise values from left stick might be messing some things up, since it's so sensitive it probably shifts slightly pretty regularly. Debug is only logging these when I hit "start game" and it successfully detects a running PoE client, but while I focus on the app window.
- When I focus on PoE instead of the app window, I don't detect any keypresses or stick movement after hitting start. No keypresses in debug console.
- I occasionally get a white screen that overlays my PoE monitor and only displays the button hints. It won't go away until I crash the app process. It's easy to replicate if you X the DOM inspector that pops up in debug mode.

**Comment by csiqueirasilva** [comment]
> When I launch with 767 (wired) it gives me an error about not being able
to find the import for i1118_736.js

I think I screwed up the import. Maybe it is something like
this require('./i1118_736.js'); instead of require('i1118_736.js');.

> If bluetooth isn't set to true when I launch with bluetooth, no input is
detected (not sure what the flag is doing so I wanted to mention this).

Yeah that one is weird! The only place that setting is used is on the ps4
gamepad file.

> When I launch with 736, I get some degree of functionality. Specifically
from debug: I can detect keypresses for all buttons and bumpers. Triggers
don't work (makes sense!). Left stick sort-of-works (moves cursor in a
circle around the center), right stick doesn't seem to be doing anything.
That said, I think the noise values from left stick might be messing some
things up, since it's so sensitive it probably shifts slightly pretty
regularly. Debug is only logging these when I hit "start game" and it
successfully detects a running PoE client, but while I focus on the app
window.

Is the circle big enough for movement or a very small circle? From what
youre saying, maybe the data index for the sticks are wrong. Anyways, just
issued a commit with the index changes. Try to pull that and see if it
works.

> When I focus on PoE instead of the app window, I don't detect any
keypresses or stick movement after hitting start. No keypresses in debug
console.

Noticed that if the application isn't reading the inputs correctly,
multiple robotjs events might be fired. If the noise is being read as
input, and it changes rapidly, so many events fire that the entire
application slows to a crawl and nothing else works. We need to fix the
inputs before tackling this.

> I occasionally get a white screen that overlays my PoE monitor and only
displays the button hints. It won't go away until I crash the app process.
It's easy to replicate if you X the DOM inspector that pops up in debug
mode.

It works like this for me too. Its expected to work in debug like that. I
just dont close the inspectors at all (can ctrl+c twice the command prompt
to quickly finish all open windows).

Em sex., 18 de set. de 2020 às 01:42, chastise <notifications@github.com>
escreveu:

**Comment by chastise** [comment]
> I think I screwed up the import. Maybe it is something like this require('./i1118_736.js'); 
> instead of require('i1118_736.js');.

This is fixed now!

> Is the circle big enough for movement or a very small circle? From what
youre saying, maybe the data index for the sticks are wrong. Anyways, just
issued a commit with the index changes. Try to pull that and see if it
works.

Yeah, I think it was movement. Things are working better with the pull though! Also, the right stick is now able to move as long as the left isn't being actively pressed!

> Noticed that if the application isn't reading the inputs correctly,
multiple robotjs events might be fired. If the noise is being read as
input, and it changes rapidly, so many events fire that the entire
application slows to a crawl and nothing else works. We need to fix the
inputs before tackling this.

Makes sense! We might be a little better with the changes now.

> Its expected to work in debug like that.

Sounds good!

**Comment by csiqueirasilva** [comment]
> This is fixed now!

Yay!

> Yeah, I think it was movement. Things are working better with the pull
though! Also, the right stick is now able to move as long as the left isn't
being actively pressed!

This is how it works: left stick for movement, right stick for "mouse" -
supposed to be used on menus, loot, etc

> Makes sense! We might be a little better with the changes now.

Do you think you can give it a shot on the development for the next hours?
I have to sleep since its already past 2 am here. Can be back on about 6 to
8 hours. Although I dont know how to test more stuff without direct access
to the device.

Em sex., 18 de set. de 2020 às 02:19, chastise <notifications@github.com>
escreveu:

**Comment by chastise** [comment]
> Do you think you can give it a shot on the development for the next hours?
I have to sleep since its already past 2 am here. Can be back on about 6 to
8 hours. Although I dont know how to test more stuff without direct access
to the device.

Oh for sure! Thank you so much for staying up and hacking on this! I'll continue looking around and see if I can make any progress. You need sleep anyways so you can do well with league launch tomorrow :-) I super appreciate you pivoting and helping me with this, and that will be true regardless of whether it's working or not!

**Comment by csiqueirasilva** [comment]
Thanks for understanding. Hopefully you can get whats left working. Would
love to see it working for you.

As a commitment to the app itself it is fun doing these kinds of things.
Cherry on top of the cake was being able to help someone tho.

Will return in about 8 hours. Good luck for now!

Em sex., 18 de set. de 2020 às 02:28, chastise <notifications@github.com>
escreveu:

**Comment by chastise** [comment]
My turn to crash. I PR'd for the L1/R1 shoulder buttons. I don't think L2/R2 will be workable with a HID driver. However, I can use JoyToKey to detect and action these buttons. Good enough! The only remaining thing as far as I can tell is getting it to correctly work with Path of Exile focused. I'll keep reading through the code to try to understand how this works / used to work once I'm up tomorrow.

**Comment by csiqueirasilva** [comment]
OK im back.

From what you put on your spreadsheet, L2/R2 share the an axis on data[9], being 128 at idle values, and going from 128 to 255 with L2 and from 128 to 0 with R2. Although what im going to propose doesnt solve the cases of them both being pressed together, in this app L2 is ESCAPE and R2 is LEFT MOUSE CLICK. So they shouldnt conflict with each other as they arent gameplay functions.

Im adding this to the code:

```
/* if it is too sensible (data[9] flickers beyond or below 128 while not pressing anything)
   the value of 128 should be adjusted to something higher for L2 and lower for R2 
   or this might work like a hair trigger (the smallest movement will trigger the keys) 
   gotta try for yourself */

if((data[9] < 128) && !pressed[KEYS.KEY_SHOULDER_RIGHT2]) { // is shoulder trigger right
	pressed[KEYS.KEY_SHOULDER_RIGHT2] = true;
	emitter.emit('keydown', KEYS.KEY_SHOULDER_RIGHT2);
} else if(pressed[KEYS.KEY_SHOULDER_RIGHT2] && (data[9] >= 128)) { // not shoulder trigger right
	pressed[KEYS.KEY_SHOULDER_RIGHT2] = false;
	emitter.emit('keyup', KEYS.KEY_SHOULDER_RIGHT2);
}
	
if((data[9] > 128) && !pressed[KEYS.KEY_SHOULDER_LEFT2]) { // is shoulder trigger right
	pressed[KEYS.KEY_SHOULDER_LEFT2] = true;
	emitter.emit('keydown', KEYS.KEY_SHOULDER_LEFT2);
} else if(pressed[KEYS.KEY_SHOULDER_LEFT2] && (data[9] <= 128)) { // not shoulder trigger right
	pressed[KEYS.KEY_SHOULDER_LEFT2] = false;
	emitter.emit('keyup', KEYS.KEY_SHOULDER_LEFT2);
}
```

I'm also adding another commit trying to set the window as always on top, but with a z-index lower than PoE window. Since i'm still not able to reproduce what your experiencing, will have to wait for you to grant feedback on that attempt to fix the PoE focus issue.

**Comment by chastise** [comment]
That trigger scheme causes the triggers to go off _immediately_ when you start to pull them. I'm a little surprised, but it looks like they behave pretty well otherwise! When one is pressed (say, left), pushing the other (right) triggers the first one (left) when it hits the halfway point. That's interesting, if a little wonky. Fortunately, you're correct that neither needs holding while using the other, so this behavior is a little buggy, but isn't really an issue. From what I've read on how HID behaves for xbox controllers, this is honestly working better than I'd hoped for :-)

Regarding the Z-axis thing, I'm still not getting any input detection outside of when I have the main app wndow focused.

**Comment by csiqueirasilva** [comment]
While you were offline, I put more information on the [developer's guide](https://github.com/csiqueirasilva/PoEController/blob/master/developers.md) about the application, but dont know if surely will help about the fix on the window focus issue. From my understanding, the issue shouldnt exist, but can be hardware related or something else.

If youd like I can take a look at whats happening. We could do a discord or something. Hit me on email if youd like to arrange something like this, we still have couple hours before heist.

**Comment by csiqueirasilva** [comment]
Hello. Today I just updated the application with a new xinput mode. Could test it with a XBOX ONE gamepad and it worked. Will upload an installation binary for it, but i'm confident this issue can be closed for now. Developer's guide was updated with the new xinput mode information.
